apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: instagram-downloader-postgres-statefulset
spec:
  selector:
    matchLabels:
      app: instagram-downloader-postgres
  serviceName: instagram-downloader-postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: instagram-downloader-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: instagram_downloader
            - name: POSTGRES_USER
              value: instagram_downloader
            - name: POSTGRES_PASSWORD
              value: SenhaMuitoForte123
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: instagram-downloader-postgres-pvc